image: python:3.8-bullseye
port: 8000
command:
   - /bin/sh
   - '-c'
   - |
      cd /opt/repos/repo    
      pip install -r requirements.txt
      python app.py
repositories:
   dataset: ds690ulp8pwm3ev
   mountPath: /opt/repos
   repositories:
      - url: https://github.com/Amgonz34/end-to-end_fraud_predictor.git
      name: repo
      ref: main
resources:
   replicas: 1
   instanceType: C5